name: Build Docker - osrm-backend-dev 

on: 
  push:
    branches:
    - 'master'
    paths:
    - 'docker/osrm-backend-dev/**'

env:
  IMAGE_NAME: osrm-backend-dev
  DOCKERFILE_PATH: docker/osrm-backend-dev/

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set IMAGE_TAG env # env IMAGE_TAG=BranchName-CommitID-Timestamp
      run: echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF} | cut -d'/' -f3)-$(echo ${GITHUB_SHA} | cut -c 1-7)-$(date -u +"%Y%m%d")
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    #- name: Build the Docker image
    #  run: cd ${DOCKERFILE_PATH} && docker build . --tag ${IMAGE_NAME}:latest

    - name: Build & Publish to Github Package
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.repository }}/${{ env.IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest,${{ env.IMAGE_TAG }}"

    - name: Build & Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest,${{ env.IMAGE_TAG }}"
