name: osrm-backend-dev

on: 
  push:
    branches:
    - 'master'
    paths:
    - 'docker/osrm-backend-dev/**'

env:
  IMAGE_NAME: osrm-backend-dev
  DOCKERFILE_PATH: docker/osrm-backend-dev/

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - name: Build the Docker image
      run: cd ${DOCKERFILE_PATH} && docker build . --tag ${IMAGE_NAME}:latest
    - name: Push to Github Package 
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: ${GITHUB_REPOSITORY}/${IMAGE_NAME}
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: "docker.pkg.github.com"

