name: osrm-backend-dev

on: 
  push:
    branches:
    - 'master'
    paths:
    - 'docker/osrm-backend-dev/**'

env:
  image-name: osrm-backend-dev
  dockerfile-path: docker/osrm-backend-dev/

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - name: Build the Docker image
      run: cd ${dockerfile-path} && docker build . --tag ${image-name}:latest
