name: Docker Image CI

on: 
  push:
    branches:
    - 'docker/**'
  create:
    branches:
    - 'docker/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get branch name
      uses: nelonoel/branch-name@v1
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test1:$(date +%s)
